// SPDX-License-Identifier: GPL-2.0
/*
 * zapscape_klp_wrapper.c - module skeleton for the CVE-2026-64561 live patch
 *
 * The patched function bodies live in mmu_klp_glob.o (generated by
 * `objtool klp diff`); this file provides the traditional klp_patch
 * registration plus the module skeleton.  Relocations for kvm.ko internal
 * symbols are resolved by objtool klp post-link (.klp.rela.* sections) and
 * the kernel's klp_resolve_symbols() at load time.
 *
 * Copyright (C) 2026 Aoripus (Beijing) Technology Co., Ltd.
 */
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/livepatch.h>
#include <linux/version.h>

/* New (fixed) function bodies, linked from mmu_klp_glob.o */
extern int direct_page_fault(void);
extern int paging64_page_fault(void);
extern int paging32_page_fault(void);
extern int ept_page_fault(void);

static struct klp_func zapscape_funcs[] = {
	{ .old_name = "direct_page_fault",	.new_func = direct_page_fault },
	{ .old_name = "paging64_page_fault",	.new_func = paging64_page_fault },
	{ .old_name = "paging32_page_fault",	.new_func = paging32_page_fault },
	{ .old_name = "ept_page_fault",		.new_func = ept_page_fault },
	{ }
};

static struct klp_object zapscape_objs[] = {
	{ .name = "kvm", .funcs = zapscape_funcs },
	{ }
};

static struct klp_patch zapscape_patch = {
	.mod = THIS_MODULE,
	.objs = zapscape_objs,
};

static int __init zapscape_klp_init(void)
{
	return klp_enable_patch(&zapscape_patch);
}

static void __exit zapscape_klp_exit(void)
{
}

module_init(zapscape_klp_init);
module_exit(zapscape_klp_exit);
MODULE_INFO(livepatch, "Y");
MODULE_LICENSE("GPL");
MODULE_AUTHOR("Aoripus (Beijing) Technology Co., Ltd.");
MODULE_DESCRIPTION("CVE-2026-64561 (Zapscape) live patch for kernel-ml 7.1.3");
MODULE_VERSION("1.0");
