// SPDX-License-Identifier: GPL-2.0
/*
 * zapscape_klp.c - CVE-2026-64561 (Zapscape) live patch for kernel-ml 7.1.3
 *
 * Replaces the four KVM page-fault handlers with the upstream-fixed
 * versions (equivalent of mainline commit 2abd5287f083):
 *   direct_page_fault / paging64_page_fault / paging32_page_fault / ept_page_fault
 *
 * The stale-root check (is_page_fault_stale) is moved AFTER
 * make_mmu_pages_available(); if reclaim zapped the in-use root, the fault
 * returns RET_PF_RETRY and restarts on a fresh root - no invalid shadow
 * children are ever created.
 *
 * Built with the in-kernel KLP toolchain (objtool klp-convert,
 * CONFIG_KLP_BUILD=y) - no kpatch needed. Relocations for kvm.ko internal
 * symbols are generated automatically at build time.
 *
 * Copyright (C) 2026 Aoripus (Beijing) Technology Co., Ltd.
 */
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/livepatch.h>
#include <linux/kvm_host.h>
#include <asm/kvm_host.h>
#include <linux/kvm_types.h>
#include <linux/uaccess.h>

#include "mmu_internal.h"
#include "spte.h"
#include "mmu.h"

/*
 * mmu_internal.h defines PTTYPE-dependent aliases (guest_walker, FNAME,
 * pt_element_t, ...).  Our expanded template bodies use the base
 * structures directly, so drop the aliases after including the header.
 */
#undef guest_walker
#undef FNAME
#undef pt_element_t

#define PTE_PREFETCH_NUM		8

/* ------------------------------------------------------------------ */
/* guest_walker structures - extracted from paging_tmpl.h (7.1.7)      */
/* ------------------------------------------------------------------ */
struct guest_walker64 {
 int level;
 unsigned max_level;
 gfn_t table_gfn[2];
 u64 ptes[2];
 u64 prefetch_ptes[PTE_PREFETCH_NUM];
 gpa_t pte_gpa[2];
 u64 __user *ptep_user[2];
 bool pte_writable[2];
 unsigned int pt_access[2];
 unsigned int pte_access;
 gfn_t gfn;
 struct x86_exception fault;
};


struct guest_walker32 {
 int level;
 unsigned max_level;
 gfn_t table_gfn[2];
 u32 ptes[2];
 u32 prefetch_ptes[PTE_PREFETCH_NUM];
 gpa_t pte_gpa[2];
 u32 __user *ptep_user[2];
 bool pte_writable[2];
 unsigned int pt_access[2];
 unsigned int pte_access;
 gfn_t gfn;
 struct x86_exception fault;
};


struct guest_walkerEPT {
 int level;
 unsigned max_level;
 gfn_t table_gfn[PT64_ROOT_MAX_LEVEL];
 u64 ptes[PT64_ROOT_MAX_LEVEL];
 u64 prefetch_ptes[PTE_PREFETCH_NUM];
 gpa_t pte_gpa[PT64_ROOT_MAX_LEVEL];
 u64 __user *ptep_user[PT64_ROOT_MAX_LEVEL];
 bool pte_writable[PT64_ROOT_MAX_LEVEL];
 unsigned int pt_access[PT64_ROOT_MAX_LEVEL];
 unsigned int pte_access;
 gfn_t gfn;
 struct x86_exception fault;
};


/*
 * kvm.ko internal (non-exported) symbols referenced by the patched
 * functions.  They are resolved at load time by the livepatch core via
 * kallsyms (CONFIG_KALLSYMS_ALL=y); the build-time relocation records are
 * generated by objtool klp-convert.
 */
extern bool kvm_mmu_is_dummy_root(hpa_t hpa);
extern int page_fault_handle_page_track(struct kvm_vcpu *vcpu,
					struct kvm_page_fault *fault);
extern int fast_page_fault(struct kvm_vcpu *vcpu,
			   struct kvm_page_fault *fault);
extern int mmu_topup_memory_caches(struct kvm_vcpu *vcpu,
				   bool maybe_indirect);
extern int kvm_mmu_faultin_pfn(struct kvm_vcpu *vcpu,
			       struct kvm_page_fault *fault,
			       unsigned int access);
extern int make_mmu_pages_available(struct kvm_vcpu *vcpu);
extern bool is_page_fault_stale(struct kvm_vcpu *vcpu,
				struct kvm_page_fault *fault);
extern int direct_map(struct kvm_vcpu *vcpu, struct kvm_page_fault *fault);
extern void kvm_mmu_finish_page_fault(struct kvm_vcpu *vcpu,
				      struct kvm_page_fault *fault, int r);
extern void shadow_page_table_clear_flood(struct kvm_vcpu *vcpu, gva_t addr);
extern struct kvm_memory_slot *kvm_vcpu_gfn_to_memslot(struct kvm_vcpu *vcpu,
						       gfn_t gfn);
extern int paging64_walk_addr(struct guest_walker64 *walker,
			      struct kvm_vcpu *vcpu, gva_t addr,
			      u32 access);
extern int paging64_fetch(struct kvm_vcpu *vcpu, struct kvm_page_fault *fault,
			  struct guest_walker64 *gw);
extern int paging64_smep(struct kvm_vcpu *vcpu, u64 spte);
extern int paging64_wp(struct kvm_vcpu *vcpu, u64 spte, bool accessed_dirty);
extern int paging32_walk_addr(struct guest_walker32 *walker,
			      struct kvm_vcpu *vcpu, gva_t addr,
			      u32 access);
extern int paging32_fetch(struct kvm_vcpu *vcpu, struct kvm_page_fault *fault,
			  struct guest_walker32 *gw);
extern int paging32_smep(struct kvm_vcpu *vcpu, u64 spte);
extern int paging32_wp(struct kvm_vcpu *vcpu, u64 spte, bool accessed_dirty);
extern int ept_walk_addr(struct guest_walkerEPT *walker,
			 struct kvm_vcpu *vcpu, gva_t addr,
			 u32 access);
extern int ept_fetch(struct kvm_vcpu *vcpu, struct kvm_page_fault *fault,
		     struct guest_walkerEPT *gw);
extern int ept_smep(struct kvm_vcpu *vcpu, u64 spte);
extern int ept_wp(struct kvm_vcpu *vcpu, u64 spte, bool accessed_dirty);

/* ------------------------------------------------------------------ */
/* ------------------------------------------------------------------ */
/* New function bodies - identical to the fixed code in linux-7.1.7    */
/* ------------------------------------------------------------------ */
static int direct_page_fault(struct kvm_vcpu *vcpu, struct kvm_page_fault *fault)
{
	int r;

	/* Dummy roots are used only for shadowing bad guest roots. */
	if (WARN_ON_ONCE(kvm_mmu_is_dummy_root(vcpu->arch.mmu->root.hpa)))
		return RET_PF_RETRY;

	if (page_fault_handle_page_track(vcpu, fault))
		return RET_PF_WRITE_PROTECTED;

	r = fast_page_fault(vcpu, fault);
	if (r != RET_PF_INVALID)
		return r;

	r = mmu_topup_memory_caches(vcpu, false);
	if (r)
		return r;

	r = kvm_mmu_faultin_pfn(vcpu, fault, ACC_ALL);
	if (r != RET_PF_CONTINUE)
		return r;

	write_lock(&vcpu->kvm->mmu_lock);

	r = make_mmu_pages_available(vcpu);
	if (r)
		goto out_unlock;

	if (is_page_fault_stale(vcpu, fault)) {
		r = RET_PF_RETRY;
		goto out_unlock;
	}

	r = direct_map(vcpu, fault);

out_unlock:
	kvm_mmu_finish_page_fault(vcpu, fault, r);
	write_unlock(&vcpu->kvm->mmu_lock);
	return r;
}


static int paging64_page_fault(struct kvm_vcpu *vcpu, struct kvm_page_fault *fault)
{
 struct guest_walker64 walker;
 int r;
 WARN_ON_ONCE(fault->is_tdp);
 r = paging64_walk_addr(&walker, vcpu, fault->addr,
        fault->error_code & ~PFERR_RSVD_MASK);
 if (!r) {
  if (!fault->prefetch)
   kvm_inject_emulated_page_fault(vcpu, &walker.fault);
  return RET_PF_RETRY;
 }
 fault->gfn = walker.gfn;
 fault->max_level = walker.level;
 fault->slot = kvm_vcpu_gfn_to_memslot(vcpu, fault->gfn);
 if (page_fault_handle_page_track(vcpu, fault)) {
  shadow_page_table_clear_flood(vcpu, fault->addr);
  return RET_PF_WRITE_PROTECTED;
 }
 r = mmu_topup_memory_caches(vcpu, true);
 if (r)
  return r;
 r = kvm_mmu_faultin_pfn(vcpu, fault, walker.pte_access);
 if (r != RET_PF_CONTINUE)
  return r;
 if (fault->write && !(walker.pte_access & ACC_WRITE_MASK) &&
     !(vcpu->arch.mmu)->cpu_role.base.cr0_wp && !fault->user && fault->slot) {
  walker.pte_access |= ACC_WRITE_MASK;
  walker.pte_access &= ~ACC_USER_MASK;
  if ((vcpu->arch.mmu)->cpu_role.ext.cr4_smep)
   walker.pte_access &= ~ACC_EXEC_MASK;
 }
 write_lock(&vcpu->kvm->mmu_lock);
 r = make_mmu_pages_available(vcpu);
 if (r)
  goto out_unlock;
 if (is_page_fault_stale(vcpu, fault)) {
  r = RET_PF_RETRY;
  goto out_unlock;
 }
 r = paging64_fetch(vcpu, fault, &walker);
out_unlock:
 kvm_mmu_finish_page_fault(vcpu, fault, r);
 write_unlock(&vcpu->kvm->mmu_lock);
 return r;
}


static int paging32_page_fault(struct kvm_vcpu *vcpu, struct kvm_page_fault *fault)
{
 struct guest_walker32 walker;
 int r;
 WARN_ON_ONCE(fault->is_tdp);
 r = paging32_walk_addr(&walker, vcpu, fault->addr,
        fault->error_code & ~PFERR_RSVD_MASK);
 if (!r) {
  if (!fault->prefetch)
   kvm_inject_emulated_page_fault(vcpu, &walker.fault);
  return RET_PF_RETRY;
 }
 fault->gfn = walker.gfn;
 fault->max_level = walker.level;
 fault->slot = kvm_vcpu_gfn_to_memslot(vcpu, fault->gfn);
 if (page_fault_handle_page_track(vcpu, fault)) {
  shadow_page_table_clear_flood(vcpu, fault->addr);
  return RET_PF_WRITE_PROTECTED;
 }
 r = mmu_topup_memory_caches(vcpu, true);
 if (r)
  return r;
 r = kvm_mmu_faultin_pfn(vcpu, fault, walker.pte_access);
 if (r != RET_PF_CONTINUE)
  return r;
 if (fault->write && !(walker.pte_access & ACC_WRITE_MASK) &&
     !(vcpu->arch.mmu)->cpu_role.base.cr0_wp && !fault->user && fault->slot) {
  walker.pte_access |= ACC_WRITE_MASK;
  walker.pte_access &= ~ACC_USER_MASK;
  if ((vcpu->arch.mmu)->cpu_role.ext.cr4_smep)
   walker.pte_access &= ~ACC_EXEC_MASK;
 }
 write_lock(&vcpu->kvm->mmu_lock);
 r = make_mmu_pages_available(vcpu);
 if (r)
  goto out_unlock;
 if (is_page_fault_stale(vcpu, fault)) {
  r = RET_PF_RETRY;
  goto out_unlock;
 }
 r = paging32_fetch(vcpu, fault, &walker);
out_unlock:
 kvm_mmu_finish_page_fault(vcpu, fault, r);
 write_unlock(&vcpu->kvm->mmu_lock);
 return r;
}


static int ept_page_fault(struct kvm_vcpu *vcpu, struct kvm_page_fault *fault)
{
 struct guest_walkerEPT walker;
 int r;
 WARN_ON_ONCE(fault->is_tdp);
 r = ept_walk_addr(&walker, vcpu, fault->addr,
        fault->error_code & ~PFERR_RSVD_MASK);
 if (!r) {
  if (!fault->prefetch)
   kvm_inject_emulated_page_fault(vcpu, &walker.fault);
  return RET_PF_RETRY;
 }
 fault->gfn = walker.gfn;
 fault->max_level = walker.level;
 fault->slot = kvm_vcpu_gfn_to_memslot(vcpu, fault->gfn);
 if (page_fault_handle_page_track(vcpu, fault)) {
  shadow_page_table_clear_flood(vcpu, fault->addr);
  return RET_PF_WRITE_PROTECTED;
 }
 r = mmu_topup_memory_caches(vcpu, true);
 if (r)
  return r;
 r = kvm_mmu_faultin_pfn(vcpu, fault, walker.pte_access);
 if (r != RET_PF_CONTINUE)
  return r;
 write_lock(&vcpu->kvm->mmu_lock);
 r = make_mmu_pages_available(vcpu);
 if (r)
  goto out_unlock;
 if (is_page_fault_stale(vcpu, fault)) {
  r = RET_PF_RETRY;
  goto out_unlock;
 }
 r = ept_fetch(vcpu, fault, &walker);
out_unlock:
 kvm_mmu_finish_page_fault(vcpu, fault, r);
 write_unlock(&vcpu->kvm->mmu_lock);
 return r;
}


/* ------------------------------------------------------------------ */
/* klp structures                                                      */
/* ------------------------------------------------------------------ */
static struct klp_func zapscape_funcs[] = {
	{ .old_name = "direct_page_fault",	.new_func = direct_page_fault },
	{ .old_name = "paging64_page_fault",	.new_func = paging64_page_fault },
	{ .old_name = "paging32_page_fault",	.new_func = paging32_page_fault },
	{ .old_name = "ept_page_fault",		.new_func = ept_page_fault },
	{ }
};

static struct klp_object zapscape_objs[] = {
	{ .name = "kvm", .funcs = zapscape_funcs },
	{ }
};

static struct klp_patch zapscape_patch = {
	.mod = THIS_MODULE,
	.objs = zapscape_objs,
};

static int __init zapscape_klp_init(void)
{
	return klp_enable_patch(&zapscape_patch);
}

static void __exit zapscape_klp_exit(void)
{
}

module_init(zapscape_klp_init);
module_exit(zapscape_klp_exit);
MODULE_INFO(livepatch, "Y");
MODULE_LICENSE("GPL");
MODULE_AUTHOR("Aoripus (Beijing) Technology Co., Ltd.");
MODULE_DESCRIPTION("CVE-2026-64561 (Zapscape) live patch for kernel-ml 7.1.3");
MODULE_VERSION("1.0");
